[project]
name = "package"
version = "0.0.0"
description = "Compare package with install versions in virtual environments"
authors = [{name = "Jeff", "email" = "<jeffwatkins2000@gmail.com>"}]
readme = "README.md"
<<<<<<< HEAD
requires-python = ">=3.13"

dependencies = [
    "appdirs>=1.4.4",
    "clipboard>=0.0.4",
    "dotenv>=0.9.9",
    "icecream>=2.1.4",
    "jedi>=0.19.2",
    "markdown>=3.8",
    "psiutils>=0.2.10",
    "pygobject>=3.54.0",
    "python-dateutil>=2.9.0.post0",
    "structlog>=25.4.0",
    "tkinterweb>=4.3.1",
=======
requires-python = ">=3.10, <3.13"

dependencies = [
    # "appdirs>=1.4.4",
    # "clipboard>=0.0.4",
    # "dotenv>=0.9.9",
    # "icecream>=2.1.4",
    # "jedi>=0.19.2",
    # "markdown>=3.8",
    # "psiutils>=0.2.10",
    # "pygobject>=3.54.0",
    # "python-dateutil>=2.9.0.post0",
    # "structlog>=25.4.0",
    # "tkinterweb>=4.3.1",
>>>>>>> 19b7e7a (Reinitialize repository with cloned files)
]

[dependency-groups]
dev = [
    "pytest",
    "jedi>=0.19.2",]

[build-system]
requires = ['uv-build']
build-backend = 'uv_build'
